const people = [
  { id: "0x1", name: "The Weeknd", role: "Artist", image: "https://i.pravatar.cc/150?u=weeknd" },
  { id: "0x2", name: "Max Martin", role: "Producer", image: "https://i.pravatar.cc/150?u=maxmartin" },
  { id: "0x3", name: "Beyoncé", role: "Artist", image: "https://i.pravatar.cc/150?u=beyonce" },
  { id: "0x4", name: "Jay-Z", role: "Featured Artist", image: "https://i.pravatar.cc/150?u=jayz" },
  { id: "0x5", name: "Pharrell Williams", role: "Producer", image: "https://i.pravatar.cc/150?u=pharrell" },
  { id: "0x6", name: "Billie Eilish", role: "Artist", image: "https://i.pravatar.cc/150?u=billie" },
  { id: "0x7", name: "Finneas O’Connell", role: "Producer", image: "https://i.pravatar.cc/150?u=finneas" },
  { id: "0x8", name: "Kendrick Lamar", role: "Artist", image: "https://i.pravatar.cc/150?u=kendrick" },
  { id: "0x9", name: "Dr. Dre", role: "Producer", image: "https://i.pravatar.cc/150?u=drdre" },
  { id: "0x06bd1006C1ACd8f32ab9599B5608f789Cb22A4F7", name: "Giancarlo Sanchez", role: "Enginner", image: "https://i.pravatar.cc/150?u=taylorswift" },
];

export const events = [
  {
    id: 1,
    title: "Blinding Lights",
    date: "2019-11-29",
    description: "Synthwave hit by The Weeknd, co-produced with Max Martin.",
    image: "https://picsum.photos/seed/blindinglights/800/600",
    people: [people[0], people[1]],
  },
  {
    id: 2,
    title: "Lemonade",
    date: "2016-04-23",
    description: "A genre-blending visual album by Beyoncé featuring Jay-Z.",
    image: "https://picsum.photos/seed/lemonade/800/600",
    people: [people[2], people[3], people[4]],
  },
  {
    id: 3,
    title: "Happier Than Ever",
    date: "2021-07-30",
    description: "Critically acclaimed album by Billie Eilish and her brother Finneas.",
    image: "https://picsum.photos/seed/happier/800/600",
    people: [people[5], people[6]],
  },
  {
    id: 4,
    title: "DAMN.",
    date: "2017-04-14",
    description: "Pulitzer-winning hip-hop album by Kendrick Lamar with Dr. Dre.",
    image: "https://picsum.photos/seed/damn/800/600",
    people: [people[7], people[8]],
  },
  {
    id: 5,
    title: "1989",
    date: "2014-10-27",
    description: "Pop transformation album by Taylor Swift featuring multiple producers.",
    image: "https://picsum.photos/seed/1989/800/600",
    people: [people[9], people[1]],
  },
  {
    id: 6,
    title: "Happy",
    date: "2013-11-21",
    description: "Feel-good funk-pop anthem written and produced by Pharrell.",
    image: "https://picsum.photos/seed/happy/800/600",
    people: [people[4]],
  },
  {
    id: 7,
    title: "The Black Album",
    date: "2003-11-14",
    description: "Seminal hip-hop album by Jay-Z with top-tier production.",
    image: "https://picsum.photos/seed/blackalbum/800/600",
    people: [people[3], people[8]],
  },
  {
    id: 8,
    title: "Starboy",
    date: "2016-11-25",
    description: "Award-winning collaboration between The Weeknd and Daft Punk.",
    image: "https://picsum.photos/seed/starboy/800/600",
    people: [people[0], people[1]],
  },
  {
    id: 9,
    title: "Montero",
    date: "2021-09-17",
    description: "Groundbreaking debut album by Lil Nas X featuring star collaborators.",
    image: "https://picsum.photos/seed/montero/800/600",
    people: [people[4], people[1]],
  },
  {
    id: 10,
    title: "When We All Fall Asleep, Where Do We Go?",
    date: "2019-03-29",
    description: "Grammy-winning debut by Billie Eilish and Finneas.",
    image: "https://picsum.photos/seed/wwafawdwg/800/600",
    people: [people[5], people[6]],
  },
];
